#! /bin/bash
# Copyright (c) 2020, by Daniel C. Nygren.
export script_name=$(/usr/bin/basename $0)
/bin/bash -c "$(/bin/cat <<"END_OF_FILE" | /usr/bin/openssl enc -aes256 -a -d -k ${0##*/} | /bin/zcat
U2FsdGVkX18hG08k59KOv69Kmu2p/Yoe+78KUyUftYqLF7NpX6w+KaDCjkc0vSgz
QtaHmQDt53PJXXGRQT/czwRaYveniadKfpgQL6dJlcgLuOyXMmDTECJ5g0OGc9Bd
x0u/ENr/M2O3z18UQcyUWF+c2MKgIiO4QPNk3mb1HN0q0mhz57Kkn/6Qxk2zEVsV
1r/Smv6+zjd0GeIniH1zE0lXQgRuBhnWh6orG0Z77/QrbOoCN3vGfPCm+s0VOVSQ
AKs1RgVmoS7qXaV3X5gKiBiPbGA/8KZl5P753g5K5g15R5i5dHkzt/elAL8ULfOJ
END_OF_FILE
)" -- "$@"
