#! /bin/bash
# Copyright (c) 2020, by Daniel C. Nygren.
export script_name=$(/usr/bin/basename $0)
/bin/bash -c "$(/bin/cat <<"END_OF_FILE" | /usr/bin/openssl enc -aes256 -a -d -k ${0##*/} | /bin/zcat
U2FsdGVkX19wnpWR4SezWKl+vCVnHmFBeH3fjnTZfgSKbgEzwBaOq07K62TY/DIX
vB89yHvtI293EZPvmh6fFxj34yin9PTdsBdqEp2nMIF9CqNmAx5lCzGYLdk9ILlw
dCeWB/fRa9rh9p9yJBwXQWcLv7WgKQ7fMX9qr0y9tYU4qeTpPcCjMg+0USgbQ2Np
lJ7FLAS0G4m3fcTv70pjUG7rO0jxxknIz0PpvakhZeho0sfLWy3bGeWITxjfNZma
C77naf718frv9lMZ/qPWWLsjdFs8JZpyD6+4i5ZaqKifQixNts3ywh+6Tgqhv0Ht
END_OF_FILE
)" -- "$@"
